travis:
  secure:
    BINSTAR_TOKEN: nU2XR9HRYFcmWGXzBCmjjddJ98HSNEOyA7yxu2uQezNQIvSurvyAn1bSTz2pZ3p/gwlgXn57zO2i1w27ie2KXHzeajIei+sTlKMpICp7Sk5VYtUQj4DzSClgMnljMMB6cuXbpbCkuXk8VkoFBtc53vUMXBY/skxeBZt5LTIZoV7C5zm5wnpvRnxMwy4Qyxcligu36yTWoq+jcgqBlGFkCixo8rt3Dbqt9sOmybbf77NPk9Bfk9LdOjXM5O5PyXokO+5sUj8veSC9FXjA9sFILLoTG4/qBIOK4rhXpRPNrY2eq+zKPYvIcJ8GVq52A1+gfISK3HSp+cSwKISh8Uk4nA7rnL6ZWyDBaZ/PNlXg//OamvVlJbW8vDUZJ2/Xe9v25uyIiTzeQuNfoLw9JbP4csWXN2n1KGVpfL8JxfuqzBKUqlE2afBZsQiDh63rIzkIZDUT8msGYPYxq+EVHORBdYEBa26aYzAfK0cf5iEnc1pVJgTx35uK1HGXtxaXryzoCOPr0rzhjBe8+0w4CkVLZGokamU5+f5hDnhcFn+yQeV7F8Bh8OLEybOXptznGsCr79NZ4MvN65YDrCaGtv+vNbQfkr0WukI6QZp1LYYY7EBxGm/GHM3/oiqWOppcSextEZ3X82EV2scIEXr9BRyp94UGfvkHLcdIFwE6xsUZ6fM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
